### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by cupnooodle** [miscellaneousbits/nsfminer#2]
Hi there,

Just a quick question. Aside from the working CUDA 11, what are the other differences from the main ethereum-mining repo? I noticed that you are also a contributor on the main one too. Is this one also dev-fee?

Thanks

**Comment by jean-m-cyr** [comment]
Neither has dev fees. This version, now called nsfminer (no stinkin' fees), improves Nvidia performance by implementing sub millisecond job switching for Nvidia. This feature is only available for AMD in the original Ethminer.
