### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by mpusat** [miscellaneousbits/nsfminer#3]
getting the following when trying to build latest version with 2019

C:\ethminer\source\ethminer>build.bat
**********************************************************************
** Visual Studio 2019 MSBuild Command Prompt
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
-- [cable ] Cable 0.2.14 initialized
CMake Error at CMakeLists.txt:2 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.

[hunter ** INTERNAL **] Configure project failed
[hunter ** INTERNAL **] [Directory:C:/ethminer/source/ethminer]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at cmake/cable/HunterGate.cmake:83 (message):
Call Stack (most recent call first):
  cmake/cable/HunterGate.cmake:93 (hunter_gate_wiki)
  cmake/cable/HunterGate.cmake:333 (hunter_gate_internal_error)
  cmake/cable/HunterGate.cmake:513 (hunter_gate_download)
  CMakeLists.txt:16 (HunterGate)

-- Configuring incomplete, errors occurred!
Error: could not load cache
Press any key to continue . . .

C:\ethminer\source\ethminer>

**Comment by jean-m-cyr** [comment]
There is a known MS problem (missing lib) with VS 2019. The latest community edition is VS 2017.

**Comment by mpusat** [comment]
Thanks will try that.

**Comment by mpusat** [comment]
Finally got everything configured to work with VS 2017 and not 2019.
